"""Background users: UEs that are not robots but share every cell with them and consume its resources.

    from isaac_net.core import NRConfig, TrafficModel, make_engine
    from isaac_net.core.background import BackgroundConfig
    bg = BackgroundConfig(n_background=8, traffic=(TrafficModel.video(fps=30, mean_frame_bytes=4000),),
                          mobility="random_waypoint", speed_mps=1.5)
    net = make_engine("L2", E, R, dev, NRConfig(background=bg))      # wrapped automatically

`n_background` UEs per cell. Their positions are drawn uniformly at every reset (in the arena, or around their own
gNB with several cells) or taken from `positions_m`, and they stay put or move by random waypoint. Their traffic
comes from the traffic models of core/traffic.py (periodic, bursty, video). The policy neither controls nor observes
them: every per-robot output keeps its shape [E, R, ...]. Two implementations, one per kind of level:

1. Ghost robots (level "L2", the NR engine). The engine runs with R + R_bg robots, where R_bg = n_background * C.
   Rows R .. R + R_bg - 1 are the background UEs: the traffic models of `traffic` run on them inside the step, the
   engine's radio sees their poses (or the path loss of their positions when the input is an SNR or a path gain),
   and they compete for RBGs in the PF scheduler, take HARQ processes, interfere with other cells and hand over like
   any robot. The user's traffic models are restricted to rows 0 .. R - 1, and every input [E, R, ...] is padded
   for the ghost rows (no policy messages, no triggers). Every output [E, R_total, ...] is sliced back to [E, R, ...].
2. Offered load (the prototype levels "L1" and "L2-legacy", every backend). The frozen schedulers have no room for
   extra rows with generated traffic, so the background enters as a fixed offered load. Each background UE u offers
   lambda_u bytes per control step (the mean rate of its traffic models) and needs the share
   rho_u = lambda_u / (K * S * BYTES_PER_SE * se(snr_u)) of its cell's RBG-slots, where se is the legacy spectral
   efficiency at its full-power SNR on one subband (the legacy path loss of its distance to the nearest gNB, no
   shadowing or fading), K the UL slots per step and S = 5 subbands. A cell's background load is
   rho_c = min(max_util, sum of rho_u over its UEs). The approximation: the background takes the share rho_c of
   every resource the robots of that cell are granted. It is applied by scaling the size of every robot message by
   1 / (1 - rho_c) of the robot's serving cell when the message is enqueued (so each granted RBG carries 1 - rho_c
   of the robot's bytes). For L1 (equal share among backlogged robots, byte service independent of the backlog)
   this is exactly a capacity reduction by 1 - rho_c. For L2-legacy it keeps the PF, SR/BSR, HARQ and fading
   dynamics and slows the robots' queues by the same factor; it does not model the background's own burstiness or
   PF competition. The load is re-evaluated each step from the background positions, and a message keeps the
   factor it was enqueued with. queue_bytes is reported in the robots' own bytes.

Step dict keys added (per step, [E, C]; C = number of cells):
  bg_n                  background UEs attached to the cell (ghosts: serving cell; load: nearest gNB)
  bg_offered_bytes      bytes the background offered this step (ghosts: accepted generated bytes on the air; load:
                        the mean offered bytes lambda)
  bg_util               share of the cell's UL resources the background used (ghosts: PRB-slots of background
                        transmissions over the PRB-slots of the step's UL data slots; load: rho_c)
  bg_delivered_bytes, bg_lost_bytes, bg_queue_bytes   ghosts only: bytes of background messages delivered, timed out
                        or dropped this step, and queued at its end (byte conservation:
                        sum offered = sum delivered + sum lost + queued)
The background positions are `bg_pos` [E, R_bg, 2] (after the step).

Randomness: placement and waypoints come from the wrapper's own counter-based streams (proto/rng.py), keyed by
(seed, env id, episode), so a partial reset redraws exactly those envs and a shard of a larger batch draws the same
numbers for an env as the unsharded engine. With n_background = 0 make_engine returns the plain engine.
"""
from __future__ import annotations

import math
from dataclasses import dataclass

import torch

from .proto import netsim as _ns
from .proto.rng import RESET, STEP, CounterRNG, mix32
from .queues import env_mask
from .traffic import Requests, TrafficModel, normalize_traffic

GHOST_LEVELS = ("L2",)
LOAD_LEVELS = ("L1", "L2-legacy")


@dataclass
class BackgroundConfig:
    """Background UEs per cell (core/background.py).

    n_background   UEs per cell (0 = none: make_engine returns the plain engine)
    placement      "random": uniform at every reset in the region; "fixed": positions_m
    positions_m    placement "fixed": one (x, y) per background UE (n_background * C entries, cell by cell), env-local m
    region         "auto": the arena with one cell, a disc of cell_radius_m around each gNB with several cells;
                   "arena": the whole arena for every UE; "cell": the disc around the UE's own gNB
    arena_m        (x0, y0, x1, y1); None = (0, 0, cell_arena_m, cell_arena_m) of NRConfig
    cell_radius_m  disc radius of region "cell"; None = cell_isd_m / 2
    traffic        traffic models of every background UE (periodic, bursty, video; no event or policy models)
    mobility       "static" or "random_waypoint" (straight to a uniform waypoint in the region at speed_mps, then a
                   new waypoint)
    speed_mps      waypoint speed
    height_m       z of the background UEs when the robots' poses are 3-D
    max_util       offered-load levels: cap on a cell's background share rho_c
    seed           seed of the placement and waypoint draws; None = derived from the engine seed
    """
    n_background: int = 0
    placement: str = "random"
    positions_m: tuple = ()
    region: str = "auto"
    arena_m: tuple | None = None
    cell_radius_m: float | None = None
    traffic: tuple = (TrafficModel.periodic(1000.0, period_ms=20.0),)
    mobility: str = "static"
    speed_mps: float = 1.0
    height_m: float = 1.5
    max_util: float = 0.95
    seed: int | None = None

    def __post_init__(self):
        assert self.n_background >= 0
        assert self.placement in ("random", "fixed") and self.region in ("auto", "arena", "cell")
        assert self.mobility in ("static", "random_waypoint") and self.speed_mps >= 0
        assert 0.0 <= self.max_util < 1.0
        self.traffic = normalize_traffic(self.traffic) or ()
        for m in self.traffic:
            if m.kind not in ("periodic", "bursty", "video"):
                raise ValueError(f"background traffic takes periodic, bursty or video models, not {m.kind}()")
            if m.robots is not None:
                raise ValueError("background traffic models apply to every background UE: drop .on(robots=...)")
        assert self.traffic, "background UEs need at least one traffic model"

    def offered_bytes_per_step(self, step_ms):
        """Mean application bytes one background UE offers per control step (sum over its models)."""
        tot = 0.0
        for m in self.traffic:
            if m.kind in ("periodic", "video"):
                tot += m.size_bytes * step_ms / m.period_ms
            else:
                on, off = m.on_off
                tot += m.size_bytes * m.burst_size * m.rate_hz * step_ms / 1000.0 * on / (on + off)
        return tot


def _pad(x, n, value):
    """Pad dim 1 of x [E, R, ...] with n entries of value."""
    if n == 0:
        return x
    pad = torch.full((x.shape[0], n) + tuple(x.shape[2:]), value, dtype=x.dtype, device=x.device)
    return torch.cat([x, pad], 1)


def _padded_trigger(f, n):
    """An event model's trigger callable, with its [E, R] mask padded for the n ghost rows."""
    def g(clock):
        m = f(clock)
        return _pad(m.to(torch.bool), n, False) if torch.is_tensor(m) and m.dim() == 2 else m
    return g


class BackgroundLoop:
    """Wrap an engine with background UEs; see the module docstring. Build it with make_engine (NRConfig.background)
    or BackgroundLoop.build(level, E, R, device, config, backend, factory=..., **kw)."""

    def __init__(self, engine, level, R, cfg, bg: BackgroundConfig, seed):
        self.engine = engine
        self.level = level
        self.mode = "ghost" if level in GHOST_LEVELS else "load"
        self.E, self.R = engine.E, R
        self.dev = torch.device(engine.dev)
        self._config = cfg
        self.bg = bg
        self.C = cfg.n_cells
        self.Nb = bg.n_background * self.C
        self.gnb = torch.tensor(cfg.gnb_xy(), dtype=torch.float32, device=self.dev)            # [C, 2]
        self.cell_of = torch.arange(self.Nb, device=self.dev) // bg.n_background                 # [Nb]
        a = bg.arena_m if bg.arena_m is not None else (0.0, 0.0, cfg.cell_arena_m, cfg.cell_arena_m)
        self.arena = tuple(float(v) for v in a)
        region = bg.region if bg.region != "auto" else ("arena" if self.C == 1 else "cell")
        self.region = region
        self.radius = float(bg.cell_radius_m if bg.cell_radius_m is not None else cfg.cell_isd_m / 2)
        if bg.placement == "fixed":
            assert len(bg.positions_m) == self.Nb, f"positions_m needs {self.Nb} entries (n_background x cells)"
            self.fixed = torch.tensor([tuple(p)[:2] for p in bg.positions_m], dtype=torch.float32, device=self.dev)
        self.step_s = cfg.control_step_ms / 1000.0
        self.rng = CounterRNG((mix32(int(seed) & 0xFFFFFFFF) ^ 0x5BD1E995) + (int(seed) >> 32), self.E, self.dev)
        self.pos = torch.zeros(self.E, self.Nb, 2, device=self.dev)
        self.wp = torch.zeros(self.E, self.Nb, 2, device=self.dev)
        self.vel = torch.zeros(self.E, self.Nb, 2, device=self.dev)
        if self.mode == "ghost":
            from .slot_tap import SlotTap
            self.tap = SlotTap.of(engine)
            self.prb_avail = float(cfg.nprb * cfg.ul_slots_per_step)
        else:
            self.lam = bg.offered_bytes_per_step(cfg.control_step_ms)
            self.K = cfg.proto_slots_per_step
            self.kappa_f = torch.ones(self.E, R, cfg.frame_buffer, device=self.dev)   # scale of every queued frame
            self.rho = torch.zeros(self.E, self.C, device=self.dev)
        self._reset_rows(None)

    # ------------------------------------------------------------------ construction
    @staticmethod
    def build(level, E, R, device, cfg, backend, factory, seed=None, **kw):
        """Build the inner engine through factory (make_engine without the wrappers) and wrap it."""
        bg = cfg.background
        if level not in GHOST_LEVELS + LOAD_LEVELS:
            raise ValueError(f"background users need a level with a capacity model: {GHOST_LEVELS + LOAD_LEVELS}; "
                             f"level {level} has none")
        if seed is None:
            seed = cfg.seed if cfg.seed is not None else int(torch.randint(0, 2 ** 62, ()).item())
        bseed = bg.seed if bg.seed is not None else seed
        inner_cfg = cfg.with_(background=None, energy=None, edge=None)
        if level in GHOST_LEVELS:
            Nb = bg.n_background * cfg.n_cells
            users = []
            for m in cfg.traffic or ():
                if m.kind == "event" and callable(m.trigger):
                    m = m.with_(trigger=_padded_trigger(m.trigger, Nb))
                users.append(m.on(tuple(range(R))) if m.robots is None else m)
            ghosts = tuple(m.on(tuple(range(R, R + Nb))).with_(det=False, tag=m.tag if m.tag is not None else 900 + i)
                           for i, m in enumerate(bg.traffic))
            inner_cfg = inner_cfg.with_(traffic=tuple(users) + ghosts)
            inner = factory(level, E, R + Nb, device, inner_cfg, backend, seed=seed, **kw)
        else:
            inner = factory(level, E, R, device, inner_cfg, backend, seed=seed, **kw)
        return BackgroundLoop(inner, level, R, cfg, bg, bseed)

    # ------------------------------------------------------------------ passthroughs
    def __getattr__(self, name):
        if name in ("engine", "bg"):
            raise AttributeError(name)
        return getattr(self.engine, name)

    @property
    def config(self):
        return self._config

    @property
    def clock(self):
        return self.engine.clock

    def queued(self):
        return self.engine.queued()[:, :self.R]

    def set_sinr_hook(self, fn, direction="ul"):
        self.engine.set_sinr_hook(fn, direction)
        self.tap.install()

    def set_env_offset(self, offset):
        """Key the placement / waypoint draws of env i by global env id offset + i (core/sharded.py)."""
        self.rng.set_env_offset(offset)

    # ------------------------------------------------------------------ positions
    def _sample(self, ids, stream, channel):
        """Uniform points in each UE's region [n, Nb, 2] (reset draws for ids, or step draws for every env)."""
        if channel == RESET:
            u = self.rng.reset_uniform(ids, stream, self.Nb, 2)
        else:
            u = self.rng.uniform(STEP, stream, self.Nb, 2)
        u = u.double()                      # float64, then float32: the same values whatever the batch size
        if self.region == "arena":
            x0, y0, x1, y1 = self.arena
            return torch.stack([x0 + (x1 - x0) * u[..., 0], y0 + (y1 - y0) * u[..., 1]], -1).float()
        r = self.radius * torch.sqrt(u[..., 0])
        th = 2 * math.pi * u[..., 1]
        return (self.gnb[self.cell_of].double() + torch.stack([r * torch.cos(th), r * torch.sin(th)], -1)).float()

    def _reset_rows(self, ids):
        """New episode for env ids (None = all): positions, waypoints, load state."""
        idx = None if ids is None else ids
        self.rng.reset(idx)
        n = self.E if idx is None else idx.numel()
        if self.bg.placement == "fixed":
            p0 = self.fixed[None].expand(n, -1, -1)
        else:
            p0 = self._sample(idx, 20, RESET)
        wp = self._sample(idx, 21, RESET) if self.bg.mobility == "random_waypoint" else p0
        m = env_mask(self.E, idx, self.dev)[:, None, None]
        full = lambda v: v if idx is None else torch.zeros_like(self.pos).index_copy_(0, idx, v)   # noqa: E731
        self.pos = torch.where(m, full(p0), self.pos)
        self.wp = torch.where(m, full(wp), self.wp)
        self.vel = torch.where(m, torch.zeros_like(self.vel), self.vel)
        if self.mode == "load":
            self.kappa_f = torch.where(m, torch.ones_like(self.kappa_f), self.kappa_f)
            self._update_load()

    def _move(self):
        """Random waypoint: every UE moves speed * step toward its waypoint; a UE that reaches it draws a new one."""
        if self.bg.mobility != "random_waypoint" or self.bg.speed_mps == 0:
            self.vel = torch.zeros_like(self.vel)
            return
        self.rng.tick(STEP)
        d = self.wp - self.pos
        dist = d.double().norm(dim=-1, keepdim=True).float()
        step = self.bg.speed_mps * self.step_s
        reach = dist <= step
        new = torch.where(reach, self.wp, (self.pos.double() + d.double() / dist.double().clamp(min=1e-9) * step).float())
        self.vel = (new - self.pos) / self.step_s
        self.pos = new
        self.wp = torch.where(reach, self._sample(None, 22, STEP), self.wp)

    def _pathloss_db(self):
        """Distance path loss of every background UE to every gNB [E, Nb, C] (log-distance, no shadowing)."""
        c = self._config
        d = (self.pos[:, :, None, :].double() - self.gnb[None, None].double()).norm(dim=-1).clamp(min=1.0)
        return (c.pl_const_db + 10 * c.pathloss_exp * torch.log10(d)).float()

    # ------------------------------------------------------------------ offered-load approximation
    def _update_load(self):
        c = self._config
        pl = self._pathloss_db()
        best, cell = pl.min(-1)                                                       # nearest gNB (lowest loss)
        snr = c.ue_tx_dbm - best.double() - c.subband_noise_dbm
        se = (0.75 * torch.log2(1 + 10 ** (snr / 10))).clamp(_ns.SE_MIN, _ns.SE_MAX)
        rho_u = self.lam / (self.K * _ns.S * _ns.BYTES_PER_SE * se)
        rho = torch.zeros(self.E, self.C, dtype=torch.float64, device=self.dev).scatter_add_(1, cell, rho_u)
        self.rho = rho.clamp(max=self.bg.max_util).float()
        self._bg_cell = cell

    def _robot_kappa(self):
        """1 / (1 - rho) of each robot's serving cell [E, R]."""
        kap = 1.0 / (1.0 - self.rho)
        if self.C == 1:
            return kap.expand(-1, self.R)
        serv = getattr(self.engine, "serv", None)
        if serv is None:
            serv = torch.zeros(self.E, self.R, dtype=torch.long, device=self.dev)
        return kap.gather(1, serv)

    def _per_cell(self, cell, v):
        return torch.zeros(self.E, self.C, dtype=v.dtype, device=self.dev).scatter_add_(1, cell, v)

    # ------------------------------------------------------------------ contract API
    def reset(self, env_ids=None):
        self.engine.reset(env_ids)
        ids = _ns.env_index(env_ids, self.E, self.dev)
        if ids is not None and ids.numel() == 0:
            return
        self._reset_rows(ids)

    def _ghost_snr(self):
        c = self._config
        return c.ue_tx_dbm - self._pathloss_db()[..., 0] - c.subband_noise_dbm

    def submit(self, t, requests, snr_db=None, **kw):
        req = requests if isinstance(requests, Requests) else Requests(send=requests)
        if self.mode == "ghost":
            n = self.Nb
            req = Requests(_pad(req.send, n, 0), None if req.det is None else _pad(req.det, n, False), req.hid)
            if snr_db is not None:
                snr_db = torch.cat([snr_db, self._ghost_snr().to(snr_db.dtype)], 1)
            for k in ("tag", "priority", "deadline_ms"):
                v = kw.get(k)
                if torch.is_tensor(v) and v.dim() == 2:
                    kw[k] = _pad(v, n, 0 if k != "deadline_ms" else float("inf"))
            return self.engine.submit(t, req, snr_db, **kw)[:, :self.R]
        # offered load: scale the new messages by 1 / (1 - rho) of the robot's serving cell
        net = self.engine
        cnt = net.queued()
        acc = net.submit(t, req, snr_db, **kw)
        slot = (torch.arange(net.rem.shape[-1], device=self.dev) == cnt[..., None]) & acc[..., None]
        kap = self._robot_kappa()[..., None]
        net.rem.copy_(torch.where(slot, net.rem * kap, net.rem))
        self.kappa_f = torch.where(slot, kap.expand_as(self.kappa_f), self.kappa_f)
        return acc

    def add_frames(self, t, send, det, hid, snr_db):
        self.submit(t, Requests(send, det, hid), snr_db)

    def add_dl_frames(self, t, nbytes, cls=None):
        n = self.Nb if self.mode == "ghost" else 0
        self.engine.add_dl_frames(t, _pad(nbytes, n, 0), None if cls is None else _pad(cls, n, 0))

    def step(self, t, x=None, cur_hid=None, **kw):
        self._move()
        if self.mode == "ghost":
            return self._step_ghost(t, x, cur_hid, **kw)
        return self._step_load(t, x, cur_hid, **kw)

    def _compact_kappa(self, keep):
        """Follow the engine's FIFO compaction: the factors of the kept message slots move to the front, in order."""
        F = self.kappa_f.shape[-1]
        order = ((~keep).long() * F + torch.arange(F, device=self.dev)).argsort(-1)
        kf = self.kappa_f.gather(-1, order)
        self.kappa_f = torch.where(keep.gather(-1, order), kf, torch.ones_like(kf))

    def _step_load(self, t, x, cur_hid, **kw):
        net = self.engine
        if cur_hid is not None:
            # legacy form: the tuple has no per-slot outputs, so the kept slots come from the FIFO before and after
            # the step. A message keeps its slot order, and messages with the same capture step of one robot were
            # enqueued at the same step with the same factor, so matching by count is exact.
            pre = net.cap.clone()
            res = net.step(t, x, cur_hid, **kw) if kw else net.step(t, x, cur_hid)
            post = net.cap
            F = pre.shape[-1]
            valid = pre >= 0
            same = pre[..., :, None] == pre[..., None, :]                                   # [E,R,F,F]
            earlier = torch.ones(F, F, dtype=torch.bool, device=self.dev).tril(-1)
            rank = (same & earlier).sum(-1)                                                 # equal caps before i
            left = (pre[..., :, None] == post[..., None, :]).sum(-1)                        # equal caps after step
            self._compact_kappa(valid & (rank < left))
            self._update_load()
            return res
        out = net.step(t, x, **kw)
        gone = out["delivered"] | out["timed_out"]
        if "dropped" in out:
            gone = gone | out["dropped"]
        self._compact_kappa((out["cap"] >= 0) & ~gone)
        out["queue_bytes"] = (net.rem / self.kappa_f).sum(-1)
        self._update_load()
        cell = self._bg_cell
        ones = torch.ones(self.E, self.Nb, device=self.dev)
        out["bg_n"] = self._per_cell(cell, ones).round().long()
        out["bg_offered_bytes"] = self._per_cell(cell, ones * self.lam)
        out["bg_util"] = self.rho.clone()
        out["bg_pos"] = self.pos.clone()
        return out

    def _step_ghost(self, t, x, cur_hid, *, snr_db=None, dl_snr_db=None, pathgain_db=None, vel=None, triggers=None):
        c, n, R = self._config, self.Nb, self.R
        gz = lambda p: p if x is None or x.shape[-1] == 2 else torch.cat(      # noqa: E731
            [p, torch.full_like(p[..., :1], self.bg.height_m)], -1)
        if x is not None:
            if x.dim() == 3:
                x = torch.cat([x, gz(self.pos).to(x.dtype)], 1)
            else:
                x = torch.cat([x, self._ghost_snr().to(x.dtype)], 1)
        if snr_db is not None:
            g = self._ghost_snr()
            g = g if snr_db.dim() == 2 else g[..., None].expand(-1, -1, snr_db.shape[-1])
            snr_db = torch.cat([snr_db, g.to(snr_db.dtype)], 1)
        if dl_snr_db is not None:
            g = self._ghost_snr() + c.dl_snr_offset_db
            g = g if dl_snr_db.dim() == 2 else g[..., None].expand(-1, -1, dl_snr_db.shape[-1])
            dl_snr_db = torch.cat([dl_snr_db, g.to(dl_snr_db.dtype)], 1)
        if pathgain_db is not None:
            pathgain_db = torch.cat([pathgain_db, -self._pathloss_db().to(pathgain_db.dtype)], 1)
        if vel is not None:
            gv = self.vel if vel.shape[-1] == 2 else torch.cat([self.vel, torch.zeros_like(self.vel[..., :1])], -1)
            vel = torch.cat([vel, gv.to(vel.dtype)], 1)
        if torch.is_tensor(triggers) and triggers.dim() == 2:
            triggers = _pad(triggers.to(torch.bool), n, False)
        elif isinstance(triggers, dict):
            triggers = {k: (_pad(v.to(torch.bool), n, False) if torch.is_tensor(v) and v.dim() == 2 else v)
                        for k, v in triggers.items()}
        self.tap.begin()
        out = self.engine.step(t, x, cur_hid, snr_db=snr_db, dl_snr_db=dl_snr_db, pathgain_db=pathgain_db,
                               vel=vel, triggers=triggers)
        if cur_hid is not None:
            newest, det_env = out
            return newest[:, :R], det_env
        E, Rt = self.E, R + n
        serv = out["serving_cell"][:, R:]
        gone = out["delivered"] | out["timed_out"] | out["dropped"]
        b = out["bytes"][:, R:].double()
        q = self.engine.net.ul.q
        qb = ((q.end - q.start) * (q.cap >= 0))[:, R:].sum(-1).double()
        res = {k: (v[:, :R] if torch.is_tensor(v) and v.dim() >= 2 and v.shape[:2] == (E, Rt) else v)
               for k, v in out.items()}
        res["bg_n"] = self._per_cell(serv, torch.ones(E, n, dtype=torch.long, device=self.dev))
        res["bg_offered_bytes"] = self._per_cell(serv, out["gen_bytes"][:, R:].double())
        res["bg_delivered_bytes"] = self._per_cell(serv, (b * out["delivered"][:, R:]).sum(-1))
        res["bg_lost_bytes"] = self._per_cell(serv, (b * (gone & ~out["delivered"])[:, R:]).sum(-1))
        res["bg_queue_bytes"] = self._per_cell(serv, qb)
        res["bg_util"] = self._per_cell(serv, self.tap.ul_prb[:, R:].double()) / self.prb_avail
        res["bg_pos"] = self.pos.clone()
        return res
