"""Presets by name, and their generated YAML copies in this folder.

    from isaac_net import NRConfig
    from isaac_net.core.presets import PRESETS, preset_path
    cfg = NRConfig.from_preset("warehouse_private_5g", ul_tpc=True)     # the Python preset with an override
    same = NRConfig.from_yaml(preset_path("warehouse_private_5g"))      # the shipped YAML copy (needs PyYAML)

PRESETS maps every name to "module:function" of its Python source: the validation presets of core/config.py and the
scenario presets of core/scenarios.py. The Python functions are the source of truth. Each <name>.yaml here is written
by scripts/export_presets.py from preset_yaml(name): the fields that differ from NRConfig(), under a header naming
the function. tests/test_config_io.py regenerates every file and fails when one differs, so they never drift.
lena_match is an alias of lena_like and has no file of its own.
"""
from __future__ import annotations

import importlib
from importlib import resources

VALIDATION_PRESETS = ("netslot_compat", "lena_like", "lena_validation", "lena_match_v2", "lena_validation_v2",
                      "srsran_like", "oai_like", "multicell")
SCENARIO_PRESETS = ("warehouse_private_5g", "factory_inf", "outdoor_campus", "urllc_control")
ALIASES = {"lena_match": "lena_like"}
PRESETS = {**{n: f"isaac_net.core.config:{n}" for n in VALIDATION_PRESETS},
           **{n: f"isaac_net.core.scenarios:{n}" for n in SCENARIO_PRESETS},
           **{a: f"isaac_net.core.config:{n}" for a, n in ALIASES.items()}}
# names with a YAML file in this folder
FILE_PRESETS = VALIDATION_PRESETS + SCENARIO_PRESETS


def preset_function(name: str):
    """The Python preset function `name` (a key of PRESETS); an unknown name raises UnknownFieldError with the
    closest names."""
    from ..config import UnknownFieldError, _suggest
    if name not in PRESETS:
        raise UnknownFieldError(f"unknown preset {name!r}{_suggest(name, PRESETS)}; presets: {', '.join(PRESETS)}")
    mod, fn = PRESETS[name].split(":")
    return getattr(importlib.import_module(mod), fn)


def preset_path(name: str):
    """The shipped YAML copy of preset `name` (an importlib.resources Traversable; works from a wheel)."""
    name = ALIASES.get(name, name)
    if name not in FILE_PRESETS:
        preset_function(name)                          # raises with the closest names
    return resources.files(__name__) / f"{name}.yaml"


def preset_yaml(name: str) -> str:
    """The text scripts/export_presets.py writes to <name>.yaml (needs PyYAML)."""
    import yaml  # noqa: F401  (fail here, not with JSON text, when PyYAML is missing)
    src = PRESETS[name].replace(":", ".")
    header = (f"Generated by scripts/export_presets.py from {src}().\n"
              "Do not edit: change the Python preset and rerun the script (tests/test_config_io.py fails\n"
              "when this file and the function disagree). It holds the fields that differ from NRConfig().\n"
              f"Load it with NRConfig.from_yaml(path), or build it with NRConfig.from_preset({name!r}).")
    return preset_function(name)().to_yaml(only_changed=True, header=header)


__all__ = ["PRESETS", "VALIDATION_PRESETS", "SCENARIO_PRESETS", "ALIASES", "FILE_PRESETS", "preset_function",
           "preset_path", "preset_yaml"]
