"""Self-contained HTML reports (inline base64 PNGs, no external files).

    from isaac_net.viz.report import from_records
    from_records(["runs/l2", "runs/l0"], "report.html")        # RecorderLoop directories, or one parent directory

from_records writes a per-run summary table (envs, robots, steps, delivered messages per env-second, loss, delay p50
/ p95, AoI p95, PRB utilization, first-transmission BLER, energy), the delay and AoI CDFs of every run, delivered vs
offered throughput, and the per-cell PRB utilization heatmap of every run that has one. The helpers (figure to
<img>, table to HTML, page skeleton) are shared with `isaac-net-bench report --html`.
"""
from __future__ import annotations

import base64
import datetime
import html
import io
import os

import numpy as np

from . import _data
from . import style as S

CSS = """body{font-family:-apple-system,Segoe UI,Helvetica,Arial,sans-serif;max-width:1100px;margin:24px auto;
padding:0 16px;color:#1d1d1f;background:#fff}h1{font-size:1.5em;margin-bottom:.2em}h2{font-size:1.15em;
margin-top:1.6em;border-bottom:1px solid #e3e3e3;padding-bottom:.2em}.sub{color:#666;font-size:.9em}
table{border-collapse:collapse;font-size:.85em;margin:.6em 0;display:block;overflow-x:auto}th,td{border:1px solid
#ddd;padding:3px 7px;text-align:right;white-space:nowrap}th{background:#f4f4f4}td.l,th.l{text-align:left}
figure{margin:.8em 0;display:inline-block;vertical-align:top}figure img{max-width:100%;height:auto}
figcaption{font-size:.85em;color:#555}code{background:#f4f4f4;padding:0 3px}"""


def fig_to_b64(fig, dpi=200) -> str:
    """PNG of a matplotlib figure as base64 text (the figure is closed afterwards)."""
    buf = io.BytesIO()
    with S.paper_style():                 # tick labels are made at draw time: draw in the paper's style
        fig.savefig(buf, format="png", dpi=dpi)
    S.pyplot().close(fig)
    return base64.b64encode(buf.getvalue()).decode("ascii")


def img_tag(fig, alt="", caption=None, width=None) -> str:
    w = f' width="{int(width)}"' if width else ""
    tag = f'<img alt="{html.escape(alt)}"{w} src="data:image/png;base64,{fig_to_b64(fig)}">'
    if caption:
        return f"<figure>{tag}<figcaption>{html.escape(caption)}</figcaption></figure>"
    return f"<figure>{tag}</figure>"


def table_html(head, rows, left=1) -> str:
    """HTML table; the first `left` columns are left-aligned."""
    def cls(i):
        return ' class="l"' if i < left else ""
    h = "".join(f"<th{cls(i)}>{html.escape(str(c))}</th>" for i, c in enumerate(head))
    body = "".join("<tr>" + "".join(f"<td{cls(i)}>{html.escape(str(c))}</td>" for i, c in enumerate(r)) + "</tr>"
                   for r in rows)
    return f"<table><thead><tr>{h}</tr></thead><tbody>{body}</tbody></table>"


def markdown_table_html(md: str, left=None) -> str:
    """A Markdown pipe table (as isaac_net.bench.report.markdown writes it) as an HTML table."""
    lines = [ln.strip() for ln in md.strip().splitlines() if ln.strip().startswith("|")]
    if len(lines) < 2:
        return f"<pre>{html.escape(md)}</pre>"
    split = lambda ln: [c.strip() for c in ln.strip("|").split("|")]   # noqa: E731
    head = split(lines[0])
    align = split(lines[1])
    if left is None:
        left = sum(1 for a in align if a.startswith(":") and not a.endswith(":"))
    return table_html(head, [split(ln) for ln in lines[2:]], left=left)


def html_document(title: str, blocks, subtitle: str | None = None) -> str:
    """A complete HTML page: title, optional subtitle, then the given HTML blocks."""
    now = datetime.datetime.now().isoformat(timespec="seconds")
    sub = f'<p class="sub">{html.escape(subtitle)}</p>' if subtitle else ""
    return (f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" '
            f'content="width=device-width,initial-scale=1"><title>{html.escape(title)}</title><style>{CSS}</style>'
            f"</head><body><h1>{html.escape(title)}</h1>{sub}{''.join(blocks)}"
            f'<p class="sub">Generated by isaac-net on {now}.</p></body></html>')


def write_html(path, text):
    d = os.path.dirname(os.path.abspath(path))
    os.makedirs(d, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    return path


def find_records(records):
    """Recorder directories from a directory, a list of them, or a parent directory holding several."""
    items = list(records) if isinstance(records, (list, tuple)) else [records]
    out = []
    for it in items:
        rd = _data.record_dir_of(it)
        if rd is not None:
            out.append(rd)
        elif isinstance(it, (str, os.PathLike)) and os.path.isdir(it):
            out += sorted(os.path.join(it, d) for d in os.listdir(it) if _data.is_record_dir(os.path.join(it, d)))
    if not out:
        raise ValueError(f"no RecorderLoop output (a directory with meta.json) in {records!r}")
    return out


def _fmt(v, spec=".3g"):
    try:
        return "n/a" if v is None or not np.isfinite(v) else format(v, spec)
    except TypeError:
        return str(v)


def summary_rows(dirs, by="config"):
    """One summary row per recorder directory (see the module docstring)."""
    from ..core.record import read_meta, read_records
    head = ["run", "level", "envs", "robots", "cells", "steps", "delivered / env-s", "lost %", "delay p50 ms",
            "delay p95 ms", "AoI p95 s", "PRB util", "BLER", "energy J / robot-s"]
    rows = []
    for d in dirs:
        m = read_meta(d)
        st = read_records(d)
        dh = _data.distributions(d, by, "delay")
        ah = _data.distributions(d, by, "aoi")
        di = next(iter(dh.values())) if dh else None
        ai = next(iter(ah.values())) if ah else None
        steps = int(st.groupby("env").steps.sum().max()) if len(st) else 0
        sec = steps * m["control_step_ms"] * 1e-3
        dl, lost = st.delivered.sum(), st.lost.sum()
        tx = st.harq_tx.sum()
        bler = np.nan if not np.isfinite(st.harq_bler).any() else np.nanmean(st.harq_bler)
        en = st.energy_j.sum() / (m["E"] * m["R"] * sec) if np.isfinite(st.energy_j).any() and sec else np.nan
        rows.append([_data.run_name(m, by, d), m["level"], m["E"], m["R"], m["C"], steps,
                     _fmt(dl / (m["E"] * sec) if sec else np.nan), _fmt(100 * lost / (dl + lost) if dl + lost else
                                                                     np.nan, ".2g"),
                     _fmt(_data.quantile(di, 0.5) if di else np.nan), _fmt(_data.quantile(di, 0.95) if di else np.nan),
                     _fmt(_data.quantile(ai, 0.95) * 1e-3 if ai else np.nan),
                     _fmt(np.nanmean(st.prb_util) if np.isfinite(st.prb_util).any() else np.nan, ".2f"),
                     _fmt(bler, ".2g") if tx else "n/a", _fmt(en)])
    return head, rows


def from_records(records, out_html, *, by="config", title="isaac-net run report"):
    """Write a self-contained HTML report of RecorderLoop output (module docstring). Returns the path."""
    from .cdf import plot_aoi_cdf, plot_delay_cdf
    from .loads import plot_cell_utilization, plot_throughput_vs_load
    from ..core.record import read_meta, read_records
    dirs = find_records(records)
    plt = S.pyplot()
    head, rows = summary_rows(dirs, by)
    blocks = ["<h2>Summary</h2>", table_html(head, rows, left=2),
              '<p class="sub">Delay and AoI quantiles from the recorder histograms (about 6% bin width); '
              "loss = timed out or dropped over delivered + lost; PRB utilization and BLER need level L2.</p>",
              "<h2>Delay and age of information</h2>"]
    for fn, cap in ((plot_delay_cdf, "Per-message delay CDF"), (plot_aoi_cdf, "Age-of-information CDF")):
        with S.paper_style():
            fig, ax = plt.subplots(figsize=(S.COL_W * 1.3, 2.4), constrained_layout=True)
        fn(dirs, by=by, ax=ax)
        blocks.append(img_tag(fig, cap, cap))
    with S.paper_style():
        fig, ax = plt.subplots(figsize=(S.COL_W * 1.3, 2.4), constrained_layout=True)
    try:
        plot_throughput_vs_load(dirs, by=by, ax=ax)
        blocks += ["<h2>Throughput</h2>", img_tag(fig, "Delivered vs offered", "Delivered vs offered throughput")]
    except ValueError:
        plt.close(fig)
    cells = []
    for d in dirs:
        m = read_meta(d)
        ce = read_records(d, "cells")
        if ce.empty or not (np.isfinite(ce.prb_util).any() or np.isfinite(ce.bg_util).any()):
            continue
        with S.paper_style():
            fig, ax = plt.subplots(figsize=(S.COL_W * 1.3, max(1.4, 0.35 * m["C"] + 0.9)), constrained_layout=True)
        name = _data.run_name(m, by, d)
        plot_cell_utilization(d, ax=ax, title=f"{name}: mean over {m['E']} envs")
        cells.append(img_tag(fig, f"cell utilization {name}", f"Per-cell UL PRB utilization, {name}"))
    if cells:
        blocks += ["<h2>Per-cell PRB utilization</h2>"] + cells
    sub = f"{len(dirs)} run(s): " + ", ".join(os.path.relpath(d) for d in dirs)
    return write_html(out_html, html_document(title, blocks, sub))
